### ISSUE TITLE
Download parking data

### ISSUE THREAD

**Issue by yakivmospan** [TeamTechnologiesLLC/AndroidChallenge#1]
This paragraph, from [Readme](https://github.com/TeamTechnologies/AndroidChallenge#challange) :

>Download parking data from the AndroidChallenge repository

shell be clarified, there are two ways this can be done in :

- With http connection (https://raw.githubusercontent.com/TeamTechnologies/AndroidChallenge/master/Belarus.json).
- Download it manually and add too app assets.

First way may require additional time to cover http connection issues (no network for instance, were developer need to provide additional functionality for download retrying).

**Comment by latemic** [comment]
Yakiv, you passed this test, because I intentionally made it unclear to check if developer will ask questions if he is concerned.

**Comment by yakivmospan** [comment]
Got it :)
